### ISSUE TITLE
Add reproducer for CSS

### ISSUE THREAD

**Issue by koppor** [Siedlerchr/javafxreproducer#25]
`#scite-error-label` is child of `#scitePane`. Color should be different.

---

Does not work:

```css
#scitePane * {
    -fx-fill: -fx-text-background-color;
}


#scite-error-label {
    -fx-text-fill: -jr-error;
}
```

---

Works:

```css
#scitePane Label {
    -fx-fill: -fx-text-background-color;
}


#scite-error-label {
    -fx-text-fill: -jr-error;
}
```

Full setting: https://github.com/JabRef/jabref/pull/11578
